#!/bin/oksh

echo "Starting.."

# TODO: unmount old root, free ramdisk

echo "Mounting pseudo-filesystems.."
mkdir /dev/pts
mount -n -t devpts -o mode=0620,gid=5,nosuid,noexec devpts /dev/pts

echo "Mounting registered filesystems.."
mount -a

echo "Starting login sessions.."
respawn getty /dev/tty1 &
respawn getty /dev/tty2 &
respawn getty /dev/tty3 &
respawn getty /dev/tty4 &
respawn getty /dev/ttyS0 &

echo "Ready."
